apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.6
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-polls-deployment
  labels:
    app: fastapi-polls-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-polls-deployment
  template:
    metadata:
      labels:
        app: fastapi-polls-deployment
    spec:
      containers:
      - name: fastapi-polls-deployment
        image: pausanchezv/fastapi-polls:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-polls-service
spec:
  selector:
    app: fastapi-polls-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010