version: "3"

services:
  redis:
    container_name: redis
    image: redis:6.2.6
    #command: redis-server --requirepass Qwer123?
    ports:
      - 6380:6379
#  polls:
#    container_name: polls
#    build: .
#    command: uvicorn app.main:app --host 0.0.0.0 --port 80
#    volumes:
#      - polls:/app
#    ports:
#      - "8000:80"
#    depends_on:
#      - redis
#
#volumes:
#  polls: