apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: pausanchezv/fastapi-polls
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        '**/*.py': .
deploy:
  kubectl:
    manifests:
      - k8s/api-deployment.yaml